### ISSUE TITLE
Shooting torches with crossbow at unknown nodes crashes

### ISSUE THREAD

**Issue by jasonkhanlar** [minetest-mods/torch_bomb#3]
```
AsyncErr: ServerThread::run Lua: Runtime error from mod '' in callback item_OnUse(): /home/user/.minetest/mods/torch_bomb/init.lua:286: attempt to index local 'under_def' (a nil value)
stack traceback:
	/home/user/.minetest/mods/torch_bomb/init.lua:286: in function 'find_target'
	/home/user/.minetest/mods/torch_bomb/init.lua:758: in function </home/ruser/.minetest/mods/torch_bomb/init.lua:736>
```

When shooting torches with a crossbow at unknown nodes (boxes that have text labeled on them reading as "unknown node"), the game crashes with that message:
	
Steps to reproduce:
- In single player local game, use a mod that creates unique node blocks
- create unique node blocks with that mod
- exit the game, disable the mod
- start the game again, shoot a torch at the unknown node block using any of the crossbows
- crash!

**Comment by FaceDeer** [comment]
Think I fixed it, torches should now stick to unknown nodes correctly. Well, as correctly as anything that deals with unknown nodes can be.
